name: release-please

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          bump-minor-pre-major: true
